const $=(s)=>document.querySelector(s); const p=new URLSearchParams(location.search);
const state={api:(p.get('api')||sessionStorage.getItem('risto.bo.api')||'http://localhost:3000').replace(/\/$/,''),token:sessionStorage.getItem('risto.bo.token')||'',data:null};
$('#apiInput').value=state.api; $('#tokenInput').value=state.token;
$('#connectButton').addEventListener('click',connect); $('#settingsButton').addEventListener('click',showSetup); $('#refreshButton').addEventListener('click',refresh); $('#createCategoryButton').addEventListener('click',createCategory); $('#createItemButton').addEventListener('click',createItem); $('#reloadTokens').addEventListener('click',loadTokens); $('#copySecret').addEventListener('click',()=>navigator.clipboard.writeText($('#secretValue').textContent||'')); $('#closeSecret').addEventListener('click',()=>$('#secretDialog').close());
if(state.token) connect();
async function connect(){ state.api=$('#apiInput').value.trim().replace(/\/$/,''); state.token=$('#tokenInput').value.trim(); if(!state.api||!state.token)return; sessionStorage.setItem('risto.bo.api',state.api);sessionStorage.setItem('risto.bo.token',state.token);try{await refresh();$('#setup').hidden=true;$('#app').hidden=false;}catch(e){$('#setupError').textContent=msg(e);} }
function showSetup(){ $('#app').hidden=true; $('#setup').hidden=false; }
async function refresh(){ state.data=await req('/v1/backoffice/restaurant'); render(); await loadTokens(); }
function render(){ const d=state.data; $('#restaurantName').textContent=d.restaurant.name; $('#restaurantSlug').textContent=d.restaurant.slug; $('#itemCount').textContent=`${d.items.length} piatti`;
  const cats=$('#categories'); cats.replaceChildren(); const select=$('#itemCategory'); select.replaceChildren(new Option('Nessuna categoria','')); for(const c of d.categories){ const row=document.createElement('div');row.className='list-row';row.innerHTML='<strong></strong><small></small>';row.querySelector('strong').textContent=c.name;row.querySelector('small').textContent=c.active?'Attiva':'Disattivata';cats.append(row);select.append(new Option(c.name,c.id)); }
  const items=$('#items');items.replaceChildren();for(const item of d.items){const row=document.createElement('div');row.className='menu-row';const copy=document.createElement('div');const name=document.createElement('strong');name.textContent=item.name;const detail=document.createElement('small');detail.textContent=`${money(item.price_minor,item.currency)} · ${item.available?'Disponibile':'Non disponibile'}`;copy.append(name,detail);const button=document.createElement('button');button.textContent=item.available?'Disattiva':'Attiva';button.addEventListener('click',()=>toggleItem(item.id,!item.available));row.append(copy,button);items.append(row);}
  const locations=$('#locations');locations.replaceChildren();for(const location of d.locations){const box=document.createElement('div');box.className='location-box';const head=document.createElement('div');head.className='location-head';const info=document.createElement('div');info.innerHTML='<strong></strong><br><small></small>';info.querySelector('strong').textContent=location.name;info.querySelector('small').textContent=location.timezone;const actions=document.createElement('div');actions.className='location-actions';const table=document.createElement('button');table.textContent='Nuovo tavolo';table.addEventListener('click',()=>newTable(location));const kds=document.createElement('button');kds.textContent='Token KDS';kds.addEventListener('click',()=>newKdsToken(location));actions.append(table,kds);head.append(info,actions);box.append(head);
    const tableRows=(d.tables||[]).filter((t)=>t.location_id===location.id); for(const t of tableRows){const row=document.createElement('div');row.className='location-row';const copy=document.createElement('div');const title=document.createElement('strong');title.textContent=t.label;const detail=document.createElement('small');detail.textContent=`QR ${t.qr_public_id}`;copy.append(title,detail);const action=document.createElement('button');action.textContent='Apri test';action.addEventListener('click',()=>window.open(`../guest-web/?api=${encodeURIComponent(state.api)}&qr=${encodeURIComponent(t.qr_public_id)}`,'_blank','noopener'));row.append(copy,action);box.append(row);} locations.append(box);}
}
async function createCategory(){const name=$('#categoryName').value.trim();if(!name)return;await req('/v1/backoffice/categories',{method:'POST',body:JSON.stringify({name,sortOrder:(state.data?.categories.length||0)*10})});$('#categoryName').value='';await refresh();}
async function createItem(){const name=$('#itemName').value.trim(),price=Math.round(Number($('#itemPrice').value)*100),currency=$('#itemCurrency').value.trim().toUpperCase();if(!name||!Number.isFinite(price))return;const body={name,priceMinor:price,currency};const description=$('#itemDescription').value.trim();if(description)body.description=description;const categoryId=$('#itemCategory').value;if(categoryId)body.categoryId=categoryId;await req('/v1/backoffice/items',{method:'POST',body:JSON.stringify(body)});$('#itemName').value='';$('#itemDescription').value='';$('#itemPrice').value='';await refresh();}
async function toggleItem(id,available){await req(`/v1/backoffice/items/${id}/availability`,{method:'PATCH',body:JSON.stringify({available})});await refresh();}
async function newTable(location){const label=prompt(`Nome/numero del tavolo in ${location.name}:`);if(!label)return;const result=await req(`/v1/backoffice/locations/${location.id}/tables`,{method:'POST',body:JSON.stringify({label})});showSecret('QR pubblico del tavolo',result.qrPublicId);await refresh();}
async function newKdsToken(location){const name=prompt('Nome della postazione KDS:','Cucina');if(!name)return;const result=await req(`/v1/backoffice/locations/${location.id}/kds-token`,{method:'POST',body:JSON.stringify({name})});showSecret(`Token KDS — ${location.name}`,result.token);await loadTokens();}
async function loadTokens(){const data=await req('/v1/backoffice/tokens');const root=$('#tokens');root.replaceChildren();for(const t of data.tokens||[]){const row=document.createElement('div');row.className='token-row';const copy=document.createElement('div');const title=document.createElement('strong');title.textContent=t.name;const detail=document.createElement('small');detail.append(document.createTextNode(`${(t.scopes||[]).join(', ')} · `));const code=document.createElement('code');code.textContent=`${t.token_prefix}…`;detail.append(code);if(t.last_used_at)detail.append(document.createTextNode(` · uso ${new Date(t.last_used_at).toLocaleString('it-IT')}`));copy.append(title,detail);const button=document.createElement('button');button.textContent=t.revoked_at?'Revocato':'Revoca';button.disabled=Boolean(t.revoked_at);button.addEventListener('click',()=>revoke(t.id));row.append(copy,button);root.append(row);}}
async function revoke(id){if(!confirm('Revocare questo accesso?'))return;await req(`/v1/backoffice/tokens/${id}`,{method:'DELETE'});await loadTokens();}
function showSecret(title,value){$('#secretTitle').textContent=title;$('#secretValue').textContent=value;$('#secretDialog').showModal();}
async function req(path,options={}){const headers=new Headers(options.headers||{});headers.set('authorization',`Bearer ${state.token}`);if(options.body)headers.set('content-type','application/json');const r=await fetch(`${state.api}${path}`,{...options,headers});const text=await r.text();let d={};try{d=text?JSON.parse(text):{};}catch{d={message:text};}if(!r.ok)throw new Error(d.message||`HTTP ${r.status}`);return d;}
function money(minor,currency){return new Intl.NumberFormat('it-IT',{style:'currency',currency}).format(Number(minor)/100)}function msg(e){return e instanceof Error?e.message:'Errore imprevisto'}
